# site settings
title: Better Help and Gardens
subtitle: for help where it's needed
email: betterhelpandgardens@gmail.com
description: High quality reliable help with a smile
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: www.betterhelpandgardens.com
author:
street_address: 
city: Eltham
state: Victoria
zip_code: 3095
country: Australia

phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
